### ISSUE TITLE
华为平板闪退

### ISSUE THREAD

**Issue by haham** [SilenceDut/KnowWeather#21]
FATAL EXCEPTION: main
                                                                            Process: com.silencedut.knowweather, PID: 26165
                                                                            java.lang.NullPointerException
                                                                                at com.silencedut.city.ui.adapter.FollowedCityData.update(FollowedCityData.java:29)
                                                                                at com.silencedut.city.ui.adapter.FollowedCityData.<init>(FollowedCityData.java:22)
                                                                                at com.silencedut.city.ui.CityModel.onWeather(CityModel.java:121)
                                                                                at com.silencedut.city.ui.CityModel.access$000(CityModel.java:29)
                                                                                at com.silencedut.city.ui.CityModel$1.onChanged(CityModel.java:40)
                                                                                at com.silencedut.city.ui.CityModel$1.onChanged(CityModel.java:36)
                                                                                at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
                                                                                at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
                                                                                at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
                                                                                at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
                                                                                at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5342)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by SilenceDut** [comment]
自己找个天气的接口，替换 项目中的就行了，原来的天气源已不可用
